name: formatted-anvils
version: '${project.version}'
main: com.funniray.anvil.FormattedAnvils
api-version: '1.16'

permissions:
  anvilformat.format:
    default: "op"
    description: "Allows formatting"
  anvilformat.noitalics:
    default: "op"
    description: "Removes Minecraft's automatic italics of renamed items"
  anvilformat.tag.any:
    default: "op"
    description: "Allows any minimessage tag."
  anvilformat.tag.color:
    default: "op"
  anvilformat.tag.gradient:
    default: "op"
  anvilformat.tag.decorations:
    default: "op"
  anvilformat.tag.newline:
    default: "op"
